import { BackgroundGradient2 } from "./background-gradient-2";
import Link from "next/link";
import { IconBrandAmazon } from "@tabler/icons-react";

export const Books = () => {
  return (
    <>
      <div className="flex flex-row flex-wrap mt-[300px] gap-[100px] justify-center items-center ">
        {BOOKS_2024.map((book, index) => (
          <BackgroundGradient2
            className="my-auto mx-auto p-[50px] text-white w-fit"
            key={index}
          >
            <div>
              <ul className="flex flex-col justify-center items-center text-justify text-xl">
                <img
                  src={book.image_cover}
                  alt={book.title}
                  width={400}
                  height={400}
                  className="rounded-2xl shadow-2xl"
                ></img>
                <h3 className="text-4xl sm:text-3xl my-[30px] font-bold">
                  {book.title}
                </h3>
                <li>{book.description}</li>
                <li>{book.year}</li>
                <Link href={book.link_amazon}>
                  <IconBrandAmazon height={100} width={60} />
                </Link>
              </ul>
            </div>
          </BackgroundGradient2>
        ))}
      </div>
    </>
  );
};

const BOOKS_2024 = [
  {
    id: 1,
    title:
      "Development and Integration of Latin America: An Odyssey Unfinished",
    description:
      "This book considers Latin American structuralism (L.A.S) as a school of thought that was proposed to explain the foundations of the development of Latin America starting from its colonial and peripheral origins. L.A.S cultivated a Latin Americanism based on the idea of liberation against the structures of domination and dependence that, since the colonial phase, fragmented the region to submit it to the interests of successive hegemonic centers. The first part of this book presents a counterpoint between the notions of capitalism and development. The second part recounts the influence of the founding fathers of L.A.S who, based on the formidable impetus of the United Nations (ECLAC), characterized the essential features of Latin American structuralism. The third part deepens the study of these features and the ideal of Latin American unity. The fourth and last part deals with the issue of political power under a republican and multidimensional conception of democracy. The author especially emphasizes the validity of the philosophy of history proposed by L.A.S not only for the study of Latin American societies but also for an adequate interpretation of the impact of the technical change generated by the current cybernetic capitalism that is transforming the world at an unprecedented scale and speed.",
    link_amazon:
      "https://www.amazon.com/Development-Integration-Latin-America-Unfinished/dp/1948915308/ref=sr_1_1?crid=2N5PJN9A9VEBO&dib=eyJ2IjoiMSJ9.EnRHHYNW3_0_zgeHkYZTjS_bZoZJ3JbUe6hqnYBR-YgkkzX2HOKjbb499qH8kQCIA8_eTrEqB6mDC05lowaRP4yGRbCr5zPOvlCvUQAv2_KcJ__LfjosYiUjLUghnt3TapNnOl9YJqNSd3VXGPdoI319V7CaYAOPSUC7tQb51oWr3V9sH67qjpqJj_ngIooKWsz2RhKjoPJ3fmipGdJHESi8yB5gcgLCZw4vGaWaVFA.WyjxISwFVMeHvHErIxn0NXC66OOptpC1kpgfu-aIcNE&dib_tag=se&keywords=armando+di+filippo&qid=1714346277&s=digital-text&sprefix=armando+di+filip%2Cdigital-text%2C264&sr=1-1-catcorr",
    link_other: "Book 1",
    image_cover: "/image/book1.jpg",
    year: 2024,
  },
  {
    id: 2,
    title:
      "El desarrollo y la integración de América Latina: Una odisea inconclusa",
    description:
      "Este libro narra la epopeya inconclusa de las naciones latinoamericanas en la búsqueda del desarrollo y de la integración.\n" +
      "El autor destaca especialmente la vigencia y validez de la filosofía de la historia propuesta por el E.L. para una adecuada interpretación del impacto del cambio técnico generado por el actual capitalismo cibernético que está transformando el mundo a una escala y velocidad sin precedentes.",
    link_amazon:
      "https://www.amazon.com/desarrollo-integración-América-Latina-inconclusa-ebook/dp/B09HN6YMN5/ref=sr_1_1?crid=2N5PJN9A9VEBO&dib=eyJ2IjoiMSJ9.9iB_FvwnwlqwnI0shvYk35seNybz3u655x0X7HIlbuhhdkAmrulWHWw0l9B9IAHe.dc4ihtJ6NbeyMbJTbJnWe_kxPmGaBPqSyqpTN8qIGzg&dib_tag=se&keywords=armando+di+filippo&qid=1714346277&s=digital-text&sprefix=armando+di+filip%2Cdigital-text%2C264&sr=1-1",
    link_other: "Book 2",
    image_cover: "/image/book2.jpg",
    year: 2021,
  },
  {
    id: 3,
    title: "Poder, capitalismo y democracia",
    description:
      "Este libro se propone examinar los vínculos entre el capitalismo y la democracia en el marco de la globalización de las sociedades humanas del tercer milenio. Expresa la mirada de un economista formado en una visión sistémica, multidimensional y dinámica de las ciencias sociales. Los cambios histórico-estructurales interrelacionados del capitalismo y la democracia pueden encuadrarse fructíferamente en dicha visión epistemológica.\n" +
      "\n" +
      "La crítica del capitalismo es el foco central de la argumentación. El capitalismo es entendido como un sistema de poder y dominación que ha estructurado la vida económica y modelado la cultura de las sociedades occidentales desde hace al menos doscientos años.\n" +
      "\n" +
      "El sistema político es la principal fuente alternativa de poder societal capaz de encausar el lucro y ponerlo al servicio de fines humanos socialmente legitimables. Pero el sistema político no puede anular o subrogar las formas económicas del poder. El lucro entendido macroeconómicamente es una medida del excedente disponible en las sociedades capitalistas para la promoción de nuevos emprendimientos productivos. Compete a las sociedades democráticas, a través del sistema político, orientar los usos sociales de ese excedente.",
    link_amazon:
      "https://www.amazon.com/Poder-capitalismo-y-democracia-Spanish-ebook/dp/B00HX2P5PI/ref=sr_1_2?crid=2N5PJN9A9VEBO&dib=eyJ2IjoiMSJ9.9iB_FvwnwlqwnI0shvYk35seNybz3u655x0X7HIlbuhhdkAmrulWHWw0l9B9IAHe.dc4ihtJ6NbeyMbJTbJnWe_kxPmGaBPqSyqpTN8qIGzg&dib_tag=se&keywords=armando+di+filippo&qid=1714346277&s=digital-text&sprefix=armando+di+filip%2Cdigital-text%2C264&sr=1-2",
    link_other: "Book 3",
    image_cover: "/image/book3.jpg",
    year: 2014,
  },
  {
    id: 4,
    title: "Integración regional: Desarrollo y equidad",
    description:
      "En este libro se examinan tanto los vínculos entre los procesos de globalización en el plano mundial y de integración en el plano regional, como sus impactos sobre las oportunidades de desarrollo de América Latina y el Caribe con especial referencia a los problemas de empleo y equidad. Distinguiendo dos tipos de acuerdos en proceso de gestación y consolidación en el nivel hemisférico, y examinando el papel del Estado-nación en la promoción de un desarrollo equitativo, el libro trata de dilucidar la verdadera función de la integración regional latinoamericana en el ámbito del desarrollo con equidad.",
    link_amazon:
      "https://www.amazon.com/Integracion-regional-Desarrollo-Economiá-demografía/dp/9682322154?ref_=ast_author_dp",
    link_other: "Book 4",
    image_cover: "/image/book4.jpg",
    year: 2000,
  },
];
